apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /data
      name: test-volume
    - mountPath: /test
      name: cache-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
  - name: cache-volume
    emptyDir: {}
