apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: default
  labels:
    app: myapp
spec:
  containers:
  - name: myapp1
    image: nginx
  - name: myapp2
    image: redis
  - name: myapp3
    image: redis
  nodeSelector:
    app: test88