apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: default
  labels:
    app: myapp
  annotations: {
    "key1" : "value1",
    "key2" : "value2"
  }
spec:
  containers:
  - name: myapp1
    image: nginx
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
      requests:
        cpu: "0.5"
        memory: "600Mi"
  - name: myapp2
    image: redis
  - name: myapp3
    image: redis
  nodeSelector:
    app: test88